### PR TITLE
Update crass to 0.10.*

### PR DESCRIPTION
**Pull request by mattbasta**

### CODE REVIEW

**Comment by mattbasta** [comment]
- Failures in Node 4 are the result of `cssshrink`.
- Failures in Node 6+ are the result of `more-css`.

**Comment by ben-eb** [comment]
Hmmm. How do we want to proceed with this?

**Comment by mattbasta** [comment]
I'm not really sure. I could look into a fix for `more-css`, but it looks unmaintained and all of the source comments are in Chinese. The problem actually doesn't stem from their codebase, though. `more-css` pulls in `clean-css` and minifies with that. I assume they do it to squeeze out every little optimization they can. The version they use is 3.2.8, which came out May of last year. The current version of clean-css is 3.4.21.

I ran this from the `css-minifiers` root:

```sh
rm -rf node_modules/more-css/node_modules/clean-css/
ln -s node_modules/more-css/node_modules/clean-css node_modules/clean-css
```

After this, all of the tests pass on Node 6+:

```
> css-minifiers@2.0.1 test /opt/css-minifiers
> tape test.js | tap-spec


  integration tests

    ✔ should minify css with clean-css
    ✔ should minify css with crass
    ✔ should minify css with css-condense
    ✔ should minify css with csso
    ✔ should minify css with cssshrink
    ✔ should minify css with csswring
    ✔ should minify css with more-css
    ✔ should minify css with ncss
    ✔ should minify css with sqwish
    ✔ should minify css with ycssmin
    ✔ should minify css with cssnano

  benchmark tests

    ✔ clean-css took 16 ms
    ✔ crass took 15 ms
    ✔ css-condense took 15 ms
    ✔ csso took 12 ms
    ✔ cssshrink took 12 ms
    ✔ csswring took 3.12 ms
    ✔ more-css took 2.59 ms
    ✔ ncss took 850 μs
    ✔ sqwish took 537 μs
    ✔ ycssmin took 483 μs
    ✔ cssnano took 16 ms

  metadata tests

    ✔ clean-css version 3.4.21
    ✔ clean-css should be cast to string
    ✔ crass version 0.10.1
    ✔ crass should be cast to string
    ✔ css-condense version 0.1.1
    ✔ css-condense should be cast to string
    ✔ cssnano version 3.8.2
    ✔ cssnano should be cast to string
    ✔ csso version 1.8.2
    ✔ csso should be cast to string
    ✔ cssshrink version 0.0.5
    ✔ cssshrink should be cast to string
    ✔ csswring version 4.2.3
    ✔ csswring should be cast to string
    ✔ more-css version 0.12.0
    ✔ more-css should be cast to string
    ✔ ncss version 1.1.1
    ✔ ncss should be cast to string
    ✔ sqwish version 0.2.2
    ✔ sqwish should be cast to string
    ✔ ycssmin version 1.0.1
    ✔ ycssmin should be cast to string


  total:     44
  passing:   44
  duration:  2.1s
```

I've filed a PR: https://github.com/army8735/more/pull/32

After I filed mine, I realized there was one filed in June for the same upgrade: https://github.com/army8735/more/pull/30

So it doesn't look likely that it'll get merged soon or at all. In that case, I guess it's up to you how to proceed. What does this mean for the ecosystem you've built on top of this module? In a matter of months Node 4 is going to leave active LTS and enter maintenance mode, leaving 6/7 the active LTS release(s) and 8+ the current releases. If the module doesn't get updated, it likely won't work in any real capacity.

Historically, `more-css` has done really well on benchmarks, but its correctness has been dubious. "Radical" isn't a term most folks strive for when building minifiers. If the goal of this repo is to show the full breadth of minifiers, I suppose I could write some code that patches more to use the new `clean-css` version. You could also point it at a fork that uses an updated version. I don't know if there's any sort of obscure package.json technical shizzle-wizzle that can be done to tell it to use a particular version of `clean-css`.

If the goal is to represent what the community is actually using, I think it might be best to remove it from the library. Nobody using the latest version of Node from April onwards (or potentially August of 2015; I haven't tested with Node 5) has been able to use more.

**Comment by ben-eb** [comment]
So my goal with this repo has been to provide a unified API across all minifiers so that we can compare results across engines and get an idea of how well (or not) they perform. I don't believe outside of things like [css-minifier-tests](https://github.com/ben-eb/css-minifier-tests) that anyone would want to use this in production, so I'm not worried too much about breaking the functionality of this module.

Ideally I'd like to keep `more-css` in here for completeness' sake but if it doesn't work on the latest versions of Node, and it won't be updated in a reasonable time frame (this is a fair assumption to make given the open pull request) then we can drop it. But I would definitely be OK with re-adding it here should the module work again on Node 6.

I'm not so interested in making sure that `more-css` works myself, as you say it's not actively maintained. If anyone cares enough to maintain a fork I would also link that from here. So we can probably drop it from this pull request and test on Node 6+?

**Comment by ben-eb** [comment]
@mattbasta Thanks for your contribution, I've released 3.0.0 with this patch. 👍

**Pull request merged**
